### PR TITLE
Additional error/input checking for PyMCX + Better error propagation

### PR DESCRIPTION
**Pull request by matinraayai**
Hello,
These new changes has better type checking of inputs and error handling that will show up as native Python errors. The errors have more informative messages for the user to understand the cause.

Please check the try/catch exception clause for MCX's OpenMP launch for correctness and absence of race conditions. Instead of a simple error_flag integer being shared between threads, a vector of strings is shared so that if an error occurs, all of their error messages will be concatenated and thrown to Python as a single runtime error.

Thanks

### CODE REVIEW

**Comment by fangq** [comment]
@matinraayai, can you change the following fields to accept integer values more than 1 (for some undocumented features):

- `issaveref`: https://github.com/fangq/mcx/blob/master/src/mcx_core.cu#L2059
- `isnormalized`: https://github.com/fangq/mcx/blob/master/src/mcx_utils.c#L1010

**Comment by fangq** [comment]
one additional cosmetic change: can you rename `gpu_info()` to `gpuinfo()` to be consistent with `mcxlab('gpuinfo')`?

**Comment by matinraayai** [comment]
@fangq I've made the requested changes.

**Comment by matinraayai** [comment]
@fangq let me see if I can add a python version of mcx_throw_exception for pymcx as well, then we can merge.

**Comment by fangq** [comment]
> @fangq let me see if I can add a python version of mcx_throw_exception for pymcx as well, then we can merge.

I think it is a good idea - so Python handles the error printing?

**Comment by fangq** [comment]
Two additional changes:

- in `pymcx.cpp` header, please change `\author` and `\copyright` to you instead of me
- in [README.md](https://github.com/fangq/mcx/blob/master/README.md#acknowledgement) and README.txt, acknowledgement section, please add `pybind11` to the external components and cite the upstream license.

**Comment by matinraayai** [comment]
> > @fangq let me see if I can add a python version of mcx_throw_exception for pymcx as well, then we can merge.
> 
> I think it is a good idea - so Python handles the error printing?
> 
> for the error handling, what is important is that when pymcx.mcx hits an error, I want to make sure that the subsequent session can still run without quitting the current session.
> 
> for host-errors, mcxlab has been working fine as expected, only in recent few years, where there was a CUDA memory error, one must restart MATLAB in order to run the next session. I think this is a driver issue, not something we can fix ...

Similar to Mex, I defined a compilation def called PYMCX_CONTAINER similar to MCX_CONTAINER that changes MCX_ERROR to instead throw a message instead of exiting. It should be working now.

I can change the macro for MCX_CONTAINER to MATLAB_MCX_CONTAINER instead (including the Makefile), but I'm not sure if your build pipelines will like the change.

**Comment by matinraayai** [comment]
> Two additional changes:
> 
>     * in `pymcx.cpp` header, please change `\author` and `\copyright` to you instead of me
> 
>     * in [README.md](https://github.com/fangq/mcx/blob/master/README.md#acknowledgement) and README.txt, acknowledgement section, please add `pybind11` to the external components and cite the upstream license.

@fangq I made these changes to my fork.

**Comment by fangq** [comment]
> I can change the macro for MCX_CONTAINER to MATLAB_MCX_CONTAINER instead (including the Makefile), but I'm not sure if your build pipelines will like the change.

is there any reason why `pymcx.cpp` can't use `MCX_CONTAINER`? this macro simply means MCX code is working in a bonded environment, which should be applicable to both MATLAB and Python. I don't like to rename it or adding new macros to do the same thing.

**Comment by matinraayai** [comment]
@fangq I can take a look again, but since I use cout and cerr directly in Python, I need another codepath that doesn't depend on Mex for flushing I/O. If that's taken care of, then I can use MCX_CONTAINER directly.

**Comment by matinraayai** [comment]
@fangq For example in the following code, MCX_CONTAINER assumes I will be using MexPrintf directly, which is not true. I need this to be changed to ```defined(MATLAB_MEX_FILE)``` so that I can use normal fprintf in PyMCX.
https://github.com/matinraayai/mcx/blob/188ac2a4a59e5dcb3f6c3b365ab3c48b363ec344/src/mcx_utils.h#L326

**Comment by matinraayai** [comment]
@fangq it seems to be working on my end on a fresh clone.
Have you been able to distribute this?

**Pull request merged**
