### PR TITLE
For MEDIA_ASGN_F2H where mua/mus are nan ensure that the provided g/n…

### PR DESCRIPTION
**Pull request by lkeegan**
… values are nontheless read

## Check List
Before you submit your pull-request, please verify and check all below items

- [ ] You have only modified the minimum number of lines that are necessary for the update; you should never add/remove white spaces to other lines that are irrelevant to the desired change.
- [ ] You have run `make pretty` (requires `astyle` in the command line) under the `src/` folder and formatted your C/C++/CUDA source codes **before every commit**; similarly, you should run `python3 -m black *.py` (`pip install black` first) to reformat all modified Python codes, or run `mh_style --fix .` (`pip install miss-hit` first) at the top-folder to format all MATLAB scripts.
- [ ] Add sufficient in-code comments following the [`doxygen` C format](https://fnch.users.sourceforge.net/doxygen_c.html)
- [ ] In addition to source code changes, you should also update the documentation ([README.md](https://github.com/fangq/mcx/blob/master/README.md), [mcx_utils.c](https://github.com/fangq/mcx/blob/v2023/src/mcx_utils.c#L5029-L5236) and/or [mcxlab.m](https://github.com/fangq/mcx/blob/v2023/mcxlab/mcxlab.m)) if any command line flag was added or changed.

If your commits included in this PR contain changes that did not follow the above guidelines, you are strongly recommended to create a clean patch using `git rebase` and `git cherry-pick` to prevent in-compliant history from appearing in the upstream code.

Moreover, you are highly recommended to 

- Add a test in the `mcx/test/testmcx.sh` script, following existing examples, to test the newly added feature; or add a MATLAB script under `mcxlab/examples` to gives examples of the desired outputs
- MCX's simulation speed is currently limited by the number of GPU registers. In your change, please consider minimizing the use of registers by reusing existing ones. CUDA compilers may not be able to optimize register counts, thus require manual optimization.
- Please create a github Issue first with detailed descriptions of the problem, testing script and proposed fixes, and link the issue with this pull-request

## Please copy/paste the corresponding Issue's URL after the below dash

-

### CODE REVIEW

**Comment by fangq** [comment]
@lkeegan, can you test my above fix in https://github.com/fangq/mcx/commit/80b57941cea33e10ab369723846108606d1cdba6 ? 

this should allow mcx to read g/n regardless mua/mus=nan or not.

**Comment by lkeegan** [comment]
With 80b5794 I see very different behaviour in the MEDIA_ASGN_F2H case with boundary padding.

I think this is because

- the nan valued mua/mus are set to zero:

https://github.com/fangq/mcx/blob/80b57941cea33e10ab369723846108606d1cdba6/src/mcx_utils.c#L3526-L3532

- but then they are overwritten with their original (nan) values:

https://github.com/fangq/mcx/blob/80b57941cea33e10ab369723846108606d1cdba6/src/mcx_utils.c#L3534-L3539

So I think the g/n values are now being read, but the boundary mua/mus values are now nan instead of 0

**Comment by fangq** [comment]
sorry for taking a while to get back to this - let me know if the above commit fixes the issue.

**Comment by lkeegan** [comment]
Thanks! With this commit the behaviour is the same as #224 - the `ref total ref=-inf` issue is fixed, but I still don't get any reflectance with b=1:

https://gist.github.com/lkeegan/ee77309c2b48883278fd9716c95d1c34

And there are also many error messages of the form:

`ERROR: should never happen! mediaid=0 idx1d=88F isreflect=1 gcfg->doreflect=1 n1=1.299805 n2=1.299805 isdet=0 flipdir[3]=2 p=(31.562723 18.700874 1.000000)[31 18 0]
`

(see https://github.com/fangq/mcx/issues/225, https://groups.google.com/g/mcx-users/c/bToGluYYdao/m/5XGk9jeHAAAJ)

**Comment by fangq** [comment]
ok, let me do more test on this.

**Comment by kdreher** [comment]
I was wondering if there are any updates on this.

**Comment by fangq** [comment]
@lkeegan, sorry for my late response.

I could not find the files `vol_bg.bin` and `vol_bg.json` in your jupyter notebook, so I wrote a simple test case based on an built-in demo

```
clear cfg;
cfg.nphoton = 1e7;
cfg.vol = uint8(ones(60, 60, 60));
cfg.srcpos = [30 30 1];
cfg.srcdir = [0 0 1];
cfg.gpuid = 1;
% cfg.gpuid='11'; % use two GPUs together
cfg.autopilot = 1;
cfg.prop = [0 0 1 1; 0.005 1 0 1.37];
cfg.tstart = 0;
cfg.tend = 5e-9;
cfg.tstep = 5e-9;

mua1 = 0.003;
mua2 = 0.1;
mua = single(reshape(repmat([mua1:(mua2 - mua1) / (60 - 1):mua2]', 60, 60), 60, 60, 60));

mus1 = 1.0;
mus2 = 5.0;
mus = single(reshape(repmat([mus1:(mus2 - mus1) / (60 - 1):mus2]', 60, 60), 60, 60, 60));

cfg.vol = reshape([mua(:)'; mus(:)'], [2 60 60 60]);
cfg.vol(3, :, :, :) = 0;
cfg.vol(4, :, :, :) = 1.37;

cfg.vol(1,:,:,1)=nan;
cfg.issaveref=1;
cfg.isreflect=1;

flux = mcxlab(cfg);
mcxplotvol(log10(flux.dref))
```

with the above script, I was able to get non-empty dref, see screenshot below - can you reproduce this in your environments (mcx binary+python)?

image

**Comment by fangq** [comment]
closing for now as the issue can no longer be reproduced.

feel free to reopen if the problem persists.

**Pull request closed without merging**
