### PR TITLE
Update MIP rendering with optimizations for lower-end GPUs

### PR DESCRIPTION
**Pull request by DouglasDwyer**
These changes contribute to the MCX Cloud web interface. They optimize the fragment shader for MIP drawing and fix a number of small issues related to rendering. In particular:

- Calculations in the fragment shader have been vectorized and unnecessary branches removed, improving performance.
- Bugs causing multiple `requestAnimationFrame` updates within a single rendering cycle have been removed, preventing `update` from being called multiple times per frame.
- The preview window has been switched to event-based rendering, and is only repainted when the user interacts with the view. This means that the GPU does not waste frames redrawing the same thing multiple times.

### CODE REVIEW

**Comment by fangq** [comment]
thank you @DouglasDwyer! 

I just updated the shader/index.html file on the http://mcx.space/cloud/ site, have one curious finding: on my Linux server (Ubuntu 18.04), with two dedicated NVIDIA TitanV GPUs+driver 470.103 and Chrome 99.0.4844.51, I noticed that the FPS dropped from 180 fps to 60.

Wondering what you see if you enable your discrete GPU.

**Comment by fangq** [comment]
here, I made both version available online:

before shader update:
http://mcx.space/cloud/preshaderopt_index.html

after shader update:
http://mcx.space/cloud/index.html

**Comment by DouglasDwyer** [comment]
@fangq, I observe similar results on my nVidia 1660 TI. Luckily, I do not believe this is a shader issue - it is a result of the bugfixes applied in this commit.
You are correct that the 60 FPS cap comes from monitor refresh rate. On my computer, with a 144 Hz refresh rate, I see a maximum of 144 FPS. The reason that higher framerates were observed prior to this commit was due to the multiple `requestAnimationFrame` calls that I removed. The framerate counter is incremented every animation frame, so the extra animation frame requests were erroneously causing the FPS counter to show higher numbers. Higher framerates in actuality might be possible by disabling V-Sync, but as far as I am aware V-Sync is controlled by the browser and cannot be modified in WebGL 2. The browser will always cap the true FPS to monitor refresh rate. Let me know if there is anything else that I can clarify - I believe this behavior demonstrates that the bugfix is working :)

**Comment by fangq** [comment]
The result on my old iGPU laptop (Ubuntu 20.04, Intel i7 5500U CPU+HD Graphics 5500) is very impressive. Please see the below screenshot - the rendering speed boosted 3x from 40 fps to 120 fps.

refresh_rate

my other laptop running NVIDIA RTX 2060 (Ubuntu 20.04, driver 470.103.01) shows a decline of fps, from 180 drop to 120, but similar to the nvidia GPU mentioned above (TitanV), the rendering and rotation is snappy, no lag at all.

my suspicion is that perhaps the "event-based" rendering limits the fps to the refresh-rate of the display?

PS: just saw your above explanation - which makes perfect sense.

**Pull request merged**
